# Generated by Django 2.0.2 on 2018-04-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0002_auto_20180419_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
