# Generated by Django 2.0.2 on 2018-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
